sudo apt-get install nodejs-legacy
sudo apt-get install npm
sudo apt-get install nmap
sudo apt-get install tree
sudo apt-get install colordiff
sudo apt-get install wine1.6
sudo apt-get install xclip
sudo apt-get install android-tools-adb
sudo apt-get install mysql-server
sudo apt-get install mysql-workbench
